apiVersion: v1
kind: Template
metadata:
  name: node
  annotations:
    description: "Node server"
    iconClass: "icon-node"
    tags: "node"
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: node
  spec:
    triggers:
    - type: ConfigChange
      configChange: {}
    source:
      contextDir: node
      type: Git
      git:
        uri: https://github.com/jpavlic/openshift-templates
        ref: master
    strategy:
      type: Docker
      DockerStrategy: {}
    output:
      to:
        kind: ImageStreamTag
        name: node:latest
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: node
  spec:
    dockerImageRepository: ''
    tags:
    - name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: node
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - master
        from:
          kind: ImageStreamTag
          name: node:latest
    - type: ConfigChange
    replicas: 1
    selector:
      browser: chrome
    template:
      metadata:
        name: node-master
        labels:
          browser: chrome
      spec:
        containers:
        - env:
          image: node
          name: master
          ports:
          - containerPort: 1337
            protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    name: selenium-node-chrome
  spec:
    selector:
      browser: chrome
    type: ClusterIP
    ports:
    - name: node-port
      port: 5555
      targetPort: 5555
      protocol: TCP
    - name: node-port-grid
      port: 4444
      targetPort: 4444
      protocol: TCP
    - name: yoda-port
      port: 1337
      targetPort: 1337
      protocol: TCP
parameters:
