apiVersion: v1
kind: Template
metadata:
  name: nodejs
  annotations:
    description: "Node server"
    iconClass: "icon-node"
    tags: "nodejs"
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: nodejs
  spec:
    triggers:
    - type: ConfigChange
      configChange: {}
    source:
      contextDir: nodejs
      type: Git
      git:
        uri: https://github.com/jpavlic/openshift-templates
        ref: master
    strategy:
      type: Docker
      DockerStrategy: {}
    output:
      to:
        kind: ImageStreamTag
        name: nodejs:latest
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: nodejs
  spec:
    dockerImageRepository: ''
    tags:
    - name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: nodejs
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - master
        from:
          kind: ImageStreamTag
          name: js:latest
    - type: ConfigChange
    replicas: 1
    selector:
      browser: chrome
    template:
      metadata:
        name: nodejs-master
        labels:
          browser: chrome
      spec:
        containers:
        - env:
          image: nodejs
          name: master
          ports:
          - containerPort: 1337
            protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    name: nodejs
  spec:
    selector:
      browser: chrome
    type: ClusterIP
    ports:
    - name: ui-port
      port: 1337
      targetPort: 1337
      protocol: TCP
parameters:
